In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [8]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

# How many different fuel types are there?

In [11]:
df.fuel_type.describe()

count         9704
unique           2
top       Gasoline
freq          4898
Name: fuel_type, dtype: object

In [ ]:
# What are they?

In [13]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [ ]:
# HOW MANY COLUMNS CONTAIN MISSING INFO?

In [15]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [16]:
# TOP FUEL EFFICIENCY IN ASIAN CARS

In [22]:
df.loc[df.origin == "Asia"].fuel_efficiency_mpg.describe()

count    3247.000000
mean       14.973830
std         2.578345
min         6.886245
25%        13.252010
50%        15.034670
75%        16.726318
max        23.759123
Name: fuel_efficiency_mpg, dtype: float64

In [ ]:
#MEDIAN VALUE FOR HORSEPOWER

In [24]:
df.horsepower.median()

np.float64(149.0)

In [25]:
#USE MOST FREQ VALUE FOR HORSEPOWER TO FILL ALL NA ELEMENTS

In [29]:
df.horsepower.value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ...
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [30]:
df.horsepower.fillna(152.0)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [32]:
df.horsepower.median()

np.float64(149.0)

 1. Select all cars from Asia
 2. Keep only 'vehicle_weight'  and 'model_year'

In [44]:
asian_cars = df.loc[df.origin == 'Asia']
asian_cars_dropped = asian_cars[["vehicle_weight", "model_year"]]
asian_cars_dropped.head()

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [49]:
# 3. Select the first 7 values as an numpy array
asian_cars_dropped[:7]

#Get the underlying NumPy array. Let's call it X.
import numpy as np

X= np.array(asian_cars_dropped[:7])
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [60]:
# 4.Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX =  np.dot(X.T, X)

# 5.Invert XTX.
XTX_inv = np.linalg.inv(XTX)

# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

#8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y
w
#9. What's the sum of all the elements of the result?
w.sum()

np.float64(0.5187709081074016)